name: Build and Deploy

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set version tag
        run: echo "VERSION=v1.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Backend
        run: docker build -t ghcr.io/mkdwns/obit-watch-backend:${{ env.VERSION }} ./backend
      
      - name: Push Backend
        run: |
          docker push ghcr.io/mkdwns/obit-watch-backend:${{ env.VERSION }}

      - name: Tag Backend latest
        run: |
          docker tag ghcr.io/mkdwns/obit-watch-backend:${{ env.VERSION }} ghcr.io/mkdwns/obit-watch-backend:latest
          docker push ghcr.io/mkdwns/obit-watch-backend:latest

      # 🔹 Build UI
      - name: Build UI
        run: docker build -t ghcr.io/mkdwns/obit-watch-ui:${{ env.VERSION }} ./frontend

      - name: Push UI
        run: docker push ghcr.io/mkdwns/obit-watch-ui:${{ env.VERSION }}

      # 🔹 Tag UI as latest
      - name: Tag UI latest
        run: |
          docker tag ghcr.io/mkdwns/obit-watch-ui:${{ env.VERSION }} ghcr.io/mkdwns/obit-watch-ui:latest
          docker push ghcr.io/mkdwns/obit-watch-ui:latest

      - name: Trigger Deploy
        run: |
          curl -X POST \
            -H "X-Deploy-Token: ${{ secrets.DEPLOY_TOKEN }}" \
            https://deploy-obit-watch.mkdwns.duckdns.org
